export enum userActionTypes {
  CHECK_AUTH_REQUEST = 'CHECK_AUTH_REQUEST',
  CHECK_AUTH_RESET = 'CHECK_AUTH_RESET',
  CHECK_AUTH_ERROR = 'CHECK_AUTH_ERROR',

  SIGN_IN_REQUEST = 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR = 'SIGN_IN_ERROR',

  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR = 'SIGN_UP_ERROR',
}
