export enum userActionTypes {
  AUTH_CHECK_REQUEST = 'AUTH_CHECK_REQUEST',
  AUTH_CHECK_RESET = 'AUTH_CHECK_RESET',
  AUTH_CHECK_ERROR = 'AUTH_CHECK_ERROR',

  SIGN_IN_REQUEST = 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR = 'SIGN_IN_ERROR',

  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR = 'SIGN_UP_ERROR',
}
