export enum userActionTypes {
  SIGN_IN_REQUEST = 'SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR = 'SIGN_IN_ERROR',

  AUTH_REQUEST = 'AUTH_REQUEST',
  AUTH_RESET = 'AUTH_RESET',
  AUTH_ERROR = 'AUTH_ERROR',
}
